Double Jump
kaizhilam/ProjectCreature pull request #86
Opened 2019-08-21 06:03 UTC by galgame-sh

2019-08-25 03:41 UTC, nodonogh requested changes
Doesn't seem to trigger when pressing space twice, I'm getting the same jump as usual
![image](https://user-images.githubusercontent.com/38229831/63645284-12462f00-c73e-11e9-88a0-289085f8b6d1.png)

2019-08-26 08:15 UTC, galgame-sh commented
> Doesn't seem to trigger when pressing space twice, I'm getting the same jump as usual
> ![image](https://user-images.githubusercontent.com/38229831/63645284-12462f00-c73e-11e9-88a0-289085f8b6d1.png)

I'm not sure, probably becuz that there no animation implemented yet, so just check if the player jumps higher when u press space twice

2019-08-27 03:53 UTC, nodonogh approved these changes
Ah yeah, looks like your last commit fixed the issue! All good!

2019-08-27 03:55 UTC, bradjamesgrant approved these changes

2019-08-28 02:00 UTC, merged